name: screen_capture_event
description: Catch screen capture (Screenshot & Screen Record) event for Android and iOS
version: 1.0.2
homepage: https://github.com/nizwar/screen_capture_event.git

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # permission_handler: ^9.2.0
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: id.nizwar.screen_capture_event
        pluginClass: ScreenCaptureEventPlugin
      ios:
        pluginClass: ScreenCaptureEventPlugin
